apiVersion: v1
kind: Service
metadata:
  name: dhaka-pm25-service
  namespace: production
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: dhaka-pm25-backend
